# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build-test-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: node-deps-v1-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --frozen-lockfile
    - run: yarn test
    
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      # You may pin to the exact commit or the version.
      # uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      uses: elgohr/Publish-Docker-Github-Action@3.02
      with:
        name: engagementteamci/node-addition-service
        username: engagementteamci
        password: ${{ secrets.DOCKERHUBPASSWORD }}
        default_branch: main
        tags: "github-actions"
